import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Announcement from "@/components/Announcement";
import Slider from "@/components/Slider";
import Categories from "@/components/Categories";
import Products from "../components/Products";
const inter = Inter({ subsets: ["latin"] });
import styled from "styled-components";
import Newsletter from "@/components/Newsletter";
export default function Home() {
  const Container = styled.div`overflow-x:hidden;width:100vw;`
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Announcement />
        <Navbar />
        <Slider />
        <Products />
        <Categories />
        <Newsletter />
      </Container>
    </>
  );
}
