import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styled from "styled-components";
import Product from "./Product/[sid].js";
import ProductLIst from "../components/ProductList/ProductLIst.js";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Announcement from "@/components/Announcement";
import Slider from "@/components/Slider";
import Categories from "@/components/Categories";
import Products from "../components/Products";
const inter = Inter({ subsets: ["latin"] });
import Newsletter from "@/components/Newsletter";
const Container1 = styled.div`overflow-x:hidden;width:100vw;padding:30px;`
const Container2 = styled.div`overflow-x:hidden;width:100vw;`
export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container1>
        <Announcement />
        <Navbar />
        <Slider />
        <Products />
        <Categories />
        <Newsletter />
      </Container1>
      <Container2>
        <ProductLIst />
      </Container2>
    </>
  );
}
