import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import styled from "styled-components";
import Product from "./Product/[sid].js";
import Home from "./Home.js"; 
import ProductLIst from "../components/ProductList/ProductLIst.js";
// import ProductList from "./pages/ProductList";
// import Register from "./pages/Register";
// import Login from "./pages/Login";
// import Cart from "./pages/Cart";
export default function Index() {
  const Container = styled.div`overflow-x:hidden;width:100vw;padding:30px;`
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      <Container>
        <ProductLIst />
      </Container>
    </>
  );
}
